//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class OPF_CAV_ISIS_F {
            name = "Retards With Guns";

            class Infantry {
                name = "Infantry";

                class OPF_CAV_RIFLE_SQUAD {
                    name = "Rifle Squad";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                };

                class OPF_CAV_CIV_SQUAD {
                    name = "Civilian Squad";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_RIFLE";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_RIFLE";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_RIFLE";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_RIFLE";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_GREN";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_GREN";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_GREN";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_GREN";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class OPF_CAV_SPECOP_SQUAD {
                    name = "Specop Squad";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_RIFLE";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_RIFLE";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_RIFLE";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_GREN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_GREN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_GREN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_GREN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_GUNNER";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_SNIPER";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_SNIPER";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LR_SNIPER";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LR_SNIPER";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class OPF_CAV_LIGHT_MOTORIZED {
                    name = "Light Motorized";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BRDM_127";
                    };
                    class Unit1 {
                        position[] = {7,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BRDM_UNARMED";
                    };
                    class Unit2 {
                        position[] = {-7,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit3 {
                        position[] = {12,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit4 {
                        position[] = {-12,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit5 {
                        position[] = {17,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-17,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {22,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-22,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit9 {
                        position[] = {27,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                    class Unit10 {
                        position[] = {-27,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                    class Unit11 {
                        position[] = {32,-35,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit12 {
                        position[] = {-32,-35,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                };

                class OPF_CAV_HEAVY_MOTORIZED {
                    name = "Heavy Motorized";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BTR";
                    };
                    class Unit1 {
                        position[] = {7,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BTR";
                    };
                    class Unit2 {
                        position[] = {-7,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit3 {
                        position[] = {12,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit4 {
                        position[] = {-12,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit5 {
                        position[] = {17,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-17,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {22,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-22,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit9 {
                        position[] = {27,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit10 {
                        position[] = {-27,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit11 {
                        position[] = {32,-37,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                    class Unit12 {
                        position[] = {-32,-37,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                };

                class OPF_CAV_CIV_MOTOR {
                    name = "Civilian Motorized";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_UNARMED";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_UNARMED";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_UNARMED";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_UNARMED";
                    };
                    class Unit4 {
                        position[] = {-10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_SPG";
                    };
                    class Unit5 {
                        position[] = {15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_LMG";
                    };
                    class Unit6 {
                        position[] = {-15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit7 {
                        position[] = {20,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit8 {
                        position[] = {-20,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit9 {
                        position[] = {25,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_RIFLE";
                    };
                    class Unit10 {
                        position[] = {-25,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_RIFLE";
                    };
                    class Unit11 {
                        position[] = {30,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_RIFLE";
                    };
                    class Unit12 {
                        position[] = {-30,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_RIFLE";
                    };
                    class Unit13 {
                        position[] = {35,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_GREN";
                    };
                    class Unit14 {
                        position[] = {-35,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_GREN";
                    };
                    class Unit15 {
                        position[] = {40,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_GREN";
                    };
                    class Unit16 {
                        position[] = {-40,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CIV_GREN";
                    };
                };

                class OPF_CAV_QRF_MOTOR {
                    name = "QRF Motorized";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_ROVER_M2";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_UNARMED";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_UNARMED";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_JEEP_UNARMED";
                    };
                    class Unit4 {
                        position[] = {-10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit5 {
                        position[] = {15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit6 {
                        position[] = {-15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit7 {
                        position[] = {20,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-20,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit9 {
                        position[] = {25,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit10 {
                        position[] = {-25,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit11 {
                        position[] = {30,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit12 {
                        position[] = {-30,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit13 {
                        position[] = {35,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                    class Unit14 {
                        position[] = {-35,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                };

                class OPF_CAV_AA_TRUCK {
                    name = "AA Group";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_TRUCK_ARMED";
                    };
                    class Unit1 {
                        position[] = {6,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TRUCK_ARMED";
                    };
                    class Unit2 {
                        position[] = {-6,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TRUCK_ARMED";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class OPF_CAV_M113_GROUP {
                    name = "Light Mechanized";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_M113";
                    };
                    class Unit1 {
                        position[] = {7,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_M113";
                    };
                    class Unit2 {
                        position[] = {-7,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit3 {
                        position[] = {12,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit4 {
                        position[] = {-12,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit5 {
                        position[] = {17,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-17,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {22,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit8 {
                        position[] = {-22,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit9 {
                        position[] = {27,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit10 {
                        position[] = {-27,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit11 {
                        position[] = {32,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                    class Unit12 {
                        position[] = {-32,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                };

                class OPF_CAV_BMP_GROUP {
                    name = "Heavy Mechanized";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SNIPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit9 {
                        position[] = {28,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BMP";
                    };
                    class Unit10 {
                        position[] = {-28,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BMP";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class OPF_CAV_T55_GROUP {
                    name = "T-55 Group";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_T55";
                    };
                    class Unit1 {
                        position[] = {9,-16,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T55";
                    };
                    class Unit2 {
                        position[] = {-9,-16,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T55";
                    };
                    class Unit3 {
                        position[] = {18,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T55";
                    };
                };

                class OPF_CAV_T55_MIXED {
                    name = "T-55 Mixed";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_T55";
                    };
                    class Unit1 {
                        position[] = {9,-16,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T55";
                    };
                    class Unit2 {
                        position[] = {-9,-16,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T34";
                    };
                    class Unit3 {
                        position[] = {17,-21,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_ZSU";
                    };
                };

                class OPF_CAV_T34_GROUP {
                    name = "T34-85 Group";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_T34";
                    };
                    class Unit1 {
                        position[] = {8,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T34";
                    };
                    class Unit2 {
                        position[] = {-8,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T34";
                    };
                    class Unit3 {
                        position[] = {16,-21,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T34";
                    };
                };

                class OPF_CAV_T34_MIXED {
                    name = "T-45-85 Mixed";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_T34";
                    };
                    class Unit1 {
                        position[] = {8,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T34";
                    };
                    class Unit2 {
                        position[] = {-8,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T55";
                    };
                    class Unit3 {
                        position[] = {16,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_ZSU";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class OPF_CAV_BM21 {
                    name = "Rocket Artillery Battery";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BM21";
                    };
                    class Unit1 {
                        position[] = {5,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BM21";
                    };
                    class Unit2 {
                        position[] = {-5,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BM21";
                    };
                    class Unit3 {
                        position[] = {10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BM21";
                    };
                };

            };

            class Naval {
                name = "Naval";

                class OPF_CAV_BOAT_SQUAD {
                    name = "Boat Squad";
                    side = 0;
                    faction = "OPF_CAV_ISIS_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_naval.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BOAT";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_LEADER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEMAN";
                    };
                };

            };

            class Air {
                name = "Air";

            };


        };

    };
};