//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class OPF_CAV_GREN_F {
        displayName = "Armed Forces of Kurdistan";
        side = 0;
        flag = "\po_main\data\ui\markers\Flag_pesh_CO.paa";
        icon = "\po_main\data\ui\markers\Flag_pesh_CO.paa";
        priority = 0;
    };
};