//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class OPF_CAV_GREN_F {
        displayName = "Armed Forces of Transnistria";
        side = 0;
        flag = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_trn_CO.paa";
        icon = "\rhsafrf\addons\rhs_main\data\flag_map\Flag_trn_CO.paa";
        priority = 0;
    };
};