//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };

    class rhs_bmd2m;
    class rhs_bmd2m_OCimport_01 : rhs_bmd2m { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmd2m_OCimport_02 : rhs_bmd2m_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics2;
            class GPMGTurretBMD2;
            class LeftBack2;
            class RightBack2;
            class MainBack2;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class rhs_btr60_msv;
    class rhs_btr60_msv_OCimport_01 : rhs_btr60_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_btr60_msv_OCimport_02 : rhs_btr60_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class rhsgref_BRDM2_msv;
    class rhsgref_BRDM2_msv_OCimport_01 : rhsgref_BRDM2_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_BRDM2_msv_OCimport_02 : rhsgref_BRDM2_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CommanderOptics;
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class rhsgref_BRDM2_ATGM_msv;
    class rhsgref_BRDM2_ATGM_msv_OCimport_01 : rhsgref_BRDM2_ATGM_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_BRDM2_ATGM_msv_OCimport_02 : rhsgref_BRDM2_ATGM_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class LOP_IRA_Landrover_M2;
    class LOP_IRA_Landrover_M2_OCimport_01 : LOP_IRA_Landrover_M2 { scope = 0; class EventHandlers; class Turrets; };
    class LOP_IRA_Landrover_M2_OCimport_02 : LOP_IRA_Landrover_M2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LOP_IRA_Landrover_SPG9;
    class LOP_IRA_Landrover_SPG9_OCimport_01 : LOP_IRA_Landrover_SPG9 { scope = 0; class EventHandlers; class Turrets; };
    class LOP_IRA_Landrover_SPG9_OCimport_02 : LOP_IRA_Landrover_SPG9_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_sprut_vdv;
    class rhs_sprut_vdv_OCimport_01 : rhs_sprut_vdv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_sprut_vdv_OCimport_02 : rhs_sprut_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_Heli_light_03_dynamicLoadout_F;
    class I_Heli_light_03_dynamicLoadout_F_OCimport_01 : I_Heli_light_03_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_light_03_dynamicLoadout_F_OCimport_02 : I_Heli_light_03_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class I_Heli_light_03_unarmed_F;
    class I_Heli_light_03_unarmed_F_OCimport_01 : I_Heli_light_03_unarmed_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_light_03_unarmed_F_OCimport_02 : I_Heli_light_03_unarmed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_Plane_Fighter_04_F;
    class I_Plane_Fighter_04_F_OCimport_01 : I_Plane_Fighter_04_F { scope = 0; class EventHandlers; };
    class I_Plane_Fighter_04_F_OCimport_02 : I_Plane_Fighter_04_F_OCimport_01 { scope = 0; class EventHandlers; };

    class I_Plane_Fighter_03_dynamicLoadout_F;
    class I_Plane_Fighter_03_dynamicLoadout_F_OCimport_01 : I_Plane_Fighter_03_dynamicLoadout_F { scope = 0; class EventHandlers; };
    class I_Plane_Fighter_03_dynamicLoadout_F_OCimport_02 : I_Plane_Fighter_03_dynamicLoadout_F_OCimport_01 { scope = 0; class EventHandlers; };

    class rhs_gaz66_ammo_msv;
    class rhs_gaz66_ammo_msv_OCimport_01 : rhs_gaz66_ammo_msv { scope = 0; class EventHandlers; };
    class rhs_gaz66_ammo_msv_OCimport_02 : rhs_gaz66_ammo_msv_OCimport_01 { scope = 0; class EventHandlers; };

    class RHS_Ural_Fuel_MSV_01;
    class RHS_Ural_Fuel_MSV_01_OCimport_01 : RHS_Ural_Fuel_MSV_01 { scope = 0; class EventHandlers; };
    class RHS_Ural_Fuel_MSV_01_OCimport_02 : RHS_Ural_Fuel_MSV_01_OCimport_01 { scope = 0; class EventHandlers; };

    class RHS_Ural_Repair_MSV_01;
    class RHS_Ural_Repair_MSV_01_OCimport_01 : RHS_Ural_Repair_MSV_01 { scope = 0; class EventHandlers; };
    class RHS_Ural_Repair_MSV_01_OCimport_02 : RHS_Ural_Repair_MSV_01_OCimport_01 { scope = 0; class EventHandlers; };

    class rhs_zsu234_aa;
    class rhs_zsu234_aa_OCimport_01 : rhs_zsu234_aa { scope = 0; class EventHandlers; class Turrets; };
    class rhs_zsu234_aa_OCimport_02 : rhs_zsu234_aa_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_kamaz5350_msv;
    class rhs_kamaz5350_msv_OCimport_01 : rhs_kamaz5350_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_kamaz5350_msv_OCimport_02 : rhs_kamaz5350_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class rhs_2s1_tv;
    class rhs_2s1_tv_OCimport_01 : rhs_2s1_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_2s1_tv_OCimport_02 : rhs_2s1_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class O_T_Boat_Armed_01_hmg_F;
    class O_T_Boat_Armed_01_hmg_F_OCimport_01 : O_T_Boat_Armed_01_hmg_F { scope = 0; class EventHandlers; class Turrets; };
    class O_T_Boat_Armed_01_hmg_F_OCimport_02 : O_T_Boat_Armed_01_hmg_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class FrontTurret;
            class RearTurret;
        };
    };


    class OPF_GREN_RIFLEMAN : O_Soldier_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_para_ttsko_urban";

        linkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_savz58p_black"};
        respawnWeapons[] = {"rhs_weap_savz58p_black"};

        magazines[] = {"rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_savz58p_black","rhsgref_acc_zendl","","",{"rhs_30Rnd_762x39mm_Savz58",30},{},""},{},{},{"rhsgref_uniform_para_ttsko_urban",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_vydra_3m",{{"rhs_30Rnd_762x39mm_Savz58_tracer",4,30},{"rhs_grenade_m1939l_f_mag",2,1},{"rhs_mag_rdg2_white",1,1}}},{"rhs_sidor",{{"rhs_30Rnd_762x39mm_Savz58_tracer",4,30},{"rhs_mag_rdg2_white",4,1},{"rhs_grenade_m1939l_f_mag",2,1}}},"rhs_6b7_1m_ess","G_Balaclava_blk",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_GREN : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_para_ttsko_urban";

        linkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m79"};
        respawnWeapons[] = {"rhs_weap_m79"};

        magazines[] = {"rhs_mag_M441_HE","rhs_mag_M441_HE"};
        respawnMagazines[] = {"rhs_mag_M441_HE","rhs_mag_M441_HE"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m79","","","",{"rhs_mag_M441_HE",1},{},""},{},{},{"rhsgref_uniform_para_ttsko_urban",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4},{"rhs_mag_M441_HE",1,1}}},{"rhs_vydra_3m",{{"rhs_mag_M433_HEDP",12,1}}},{"rhs_sidor",{{"rhs_mag_M433_HEDP",20,1}}},"rhs_6b7_1m_ess","G_Balaclava_blk",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_GUNNER : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Gunner";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_para_ttsko_urban";

        linkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_mg42"};
        respawnWeapons[] = {"rhs_weap_mg42"};

        magazines[] = {"rhsgref_50Rnd_792x57_SmE_drum","rhsgref_50Rnd_792x57_SmE_drum"};
        respawnMagazines[] = {"rhsgref_50Rnd_792x57_SmE_drum","rhsgref_50Rnd_792x57_SmE_drum"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_mg42","","","",{"rhsgref_50Rnd_792x57_SmE_drum",50},{},""},{},{},{"rhsgref_uniform_para_ttsko_urban",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_vydra_3m",{{"rhsgref_50Rnd_792x57_SmE_drum",4,50}}},{"rhs_sidor",{{"rhsgref_50Rnd_792x57_SmE_drum",6,50}}},"rhs_6b7_1m_ess","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_LEADER : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Leader";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_para_ttsko_urban";

        linkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_l1a1"};
        respawnWeapons[] = {"rhs_weap_l1a1"};

        magazines[] = {"rhs_mag_20Rnd_762x51_m80_fnfal","rhs_mag_20Rnd_762x51_m80_fnfal"};
        respawnMagazines[] = {"rhs_mag_20Rnd_762x51_m80_fnfal","rhs_mag_20Rnd_762x51_m80_fnfal"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_l1a1","rhsgref_acc_falMuzzle_l1a1","","",{"rhs_mag_20Rnd_762x51_m80_fnfal",20},{},""},{},{},{"rhsgref_uniform_para_ttsko_urban",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_vydra_3m",{{"rhs_mag_20Rnd_762x51_m62_fnfal",4,20}}},{"rhs_sidor",{{"rhs_mag_20Rnd_762x51_m62_fnfal",6,20}}},"rhs_6b7_1m_ess","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_SQDM : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "SQDM";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_para_ttsko_urban";

        linkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhs_6b7_1m_ess","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_l1a1"};
        respawnWeapons[] = {"rhs_weap_l1a1"};

        magazines[] = {"rhs_mag_20Rnd_762x51_m80_fnfal","rhs_mag_20Rnd_762x51_m80_fnfal"};
        respawnMagazines[] = {"rhs_mag_20Rnd_762x51_m80_fnfal","rhs_mag_20Rnd_762x51_m80_fnfal"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_l1a1","rhsgref_acc_falMuzzle_l1a1","","rhsgref_acc_l1a1_l2a2",{"rhs_mag_20Rnd_762x51_m80_fnfal",20},{},""},{},{},{"rhsgref_uniform_para_ttsko_urban",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_vydra_3m",{{"rhs_mag_20Rnd_762x51_m62_fnfal",4,20}}},{"rhs_sidor",{{"rhs_mag_20Rnd_762x51_m62_fnfal",6,20}}},"rhs_6b7_1m_ess","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_CREWMAN : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_para_ttsko_urban";

        linkedItems[] = {"rhs_6sh46","rhs_tsh4","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6sh46","rhs_tsh4","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m3a1"};
        respawnWeapons[] = {"rhs_weap_m3a1"};

        magazines[] = {"rhsgref_30rnd_1143x23_M1911B_SMG","rhsgref_30rnd_1143x23_M1911B_SMG"};
        respawnMagazines[] = {"rhsgref_30rnd_1143x23_M1911B_SMG","rhsgref_30rnd_1143x23_M1911B_SMG"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m3a1","","","",{"rhsgref_30rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"rhsgref_uniform_para_ttsko_urban",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_6sh46",{{"rhsgref_30rnd_1143x23_M1911B_SMG",2,30}}},{"rhs_sidor",{{"ToolKit",1},{"rhsgref_30rnd_1143x23_M1T_SMG",2,30}}},"rhs_tsh4","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_PILOT : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_para_ttsko_urban";

        linkedItems[] = {"rhs_6sh46","rhs_zsh7a_mike_green_alt","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6sh46","rhs_zsh7a_mike_green_alt","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m3a1"};
        respawnWeapons[] = {"rhs_weap_m3a1"};

        magazines[] = {"rhsgref_30rnd_1143x23_M1911B_SMG","rhsgref_30rnd_1143x23_M1911B_SMG"};
        respawnMagazines[] = {"rhsgref_30rnd_1143x23_M1911B_SMG","rhsgref_30rnd_1143x23_M1911B_SMG"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m3a1","","","",{"rhsgref_30rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"rhsgref_uniform_para_ttsko_urban",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_6sh46",{{"rhsgref_30rnd_1143x23_M1911B_SMG",2,30}}},{"rhs_sidor",{{"ToolKit",1},{"rhsgref_30rnd_1143x23_M1T_SMG",2,30}}},"rhs_zsh7a_mike_green_alt","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_SPECOP_RIFLE : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Rifle";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_specter";

        linkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"rhs_weap_ak105_zenitco01"};
        respawnWeapons[] = {"rhs_weap_ak105_zenitco01"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_30Rnd_545x39_7N10_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_30Rnd_545x39_7N10_AK"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak105_zenitco01","rhs_acc_tgpa","rhs_acc_perst3","rhs_acc_okp7_dovetail",{"rhs_30Rnd_545x39_7N10_AK",30},{},"rhs_acc_grip_rk2"},{},{},{"rhsgref_uniform_specter",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_vydra_3m",{{"rhs_30Rnd_545x39_7N10_AK",4,30}}},{"rhs_sidor",{{"rhsgref_30rnd_1143x23_M1T_SMG",2,30},{"rhs_30Rnd_545x39_7N10_AK",4,30}}},"rhsgref_patrolcap_specter","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_SPECOP_GREN : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Grenadier";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_specter";

        linkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"rhs_weap_ak74mr_gp25"};
        respawnWeapons[] = {"rhs_weap_ak74mr_gp25"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_30Rnd_545x39_7N10_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_30Rnd_545x39_7N10_AK"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74mr_gp25","rhs_acc_tgpa","rhs_acc_perst3","rhs_acc_okp7_picatinny",{"rhs_30Rnd_545x39_7N10_AK",30},{},""},{},{},{"rhsgref_uniform_specter",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4},{"rhs_VOG25",1,1}}},{"rhs_vydra_3m",{{"rhs_30Rnd_545x39_7N10_AK",4,30},{"rhs_VOG25",2,1},{"rhs_VOG25P",8,1}}},{"rhs_sidor",{{"rhsgref_30rnd_1143x23_M1T_SMG",2,30},{"rhs_VOG25P",12,1},{"rhs_30Rnd_545x39_7N10_AK",4,30}}},"rhsgref_patrolcap_specter","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_SPECOP_GUNNER : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Gunner";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_specter";

        linkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"rhs_weap_mg42"};
        respawnWeapons[] = {"rhs_weap_mg42"};

        magazines[] = {"rhsgref_50Rnd_792x57_SmE_drum","rhsgref_50Rnd_792x57_SmE_drum"};
        respawnMagazines[] = {"rhsgref_50Rnd_792x57_SmE_drum","rhsgref_50Rnd_792x57_SmE_drum"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_mg42","","","",{"rhsgref_50Rnd_792x57_SmE_drum",50},{},""},{},{},{"rhsgref_uniform_specter",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_vydra_3m",{{"rhsusf_mag_10Rnd_STD_50BMG_mk211",1,10},{"rhsgref_50Rnd_792x57_SmE_drum",2,50}}},{"rhs_sidor",{{"rhsgref_50Rnd_792x57_SmE_drum",7,50}}},"rhsgref_patrolcap_specter","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_SPECOP_LR_SNIPER : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop LR Sniper";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_specter";

        linkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"rhs_weap_M107"};
        respawnWeapons[] = {"rhs_weap_M107"};

        magazines[] = {"rhsusf_mag_10Rnd_STD_50BMG_M33","rhsusf_mag_10Rnd_STD_50BMG_M33"};
        respawnMagazines[] = {"rhsusf_mag_10Rnd_STD_50BMG_M33","rhsusf_mag_10Rnd_STD_50BMG_M33"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_M107","","","rhsusf_acc_premier",{"rhsusf_mag_10Rnd_STD_50BMG_M33",10},{},""},{},{},{"rhsgref_uniform_specter",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4}}},{"rhs_vydra_3m",{{"rhsusf_mag_10Rnd_STD_50BMG_mk211",1,10}}},{"rhs_sidor",{{"rhsusf_mag_10Rnd_STD_50BMG_mk211",3,10}}},"rhsgref_patrolcap_specter","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_SPECOP_SNIPER : OPF_GREN_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Sniper";
        side = 0;
        faction = "OPF_CAV_GREN_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhsgref_uniform_specter";

        linkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"rhs_vydra_3m","rhsgref_patrolcap_specter","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"rhs_weap_svds"};
        respawnWeapons[] = {"rhs_weap_svds"};

        magazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_10Rnd_762x54mmR_7N1"};
        respawnMagazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_10Rnd_762x54mmR_7N1"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_svds","rhs_acc_tgpv2","","rhs_acc_pso1m21",{"rhs_10Rnd_762x54mmR_7N1",10},{},""},{},{},{"rhsgref_uniform_specter",{{"ACE_quikclot",20},{"ACE_morphine",2},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_tourniquet",4},{"rhs_10Rnd_762x54mmR_7N1",1,10}}},{"rhs_vydra_3m",{{"rhs_VOG25P",4,1},{"rhs_10Rnd_762x54mmR_7N1",8,10}}},{"rhs_sidor",{{"rhs_10Rnd_762x54mmR_7N1",14,10}}},"rhsgref_patrolcap_specter","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_BMD : rhs_bmd2m_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BMD";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_CREWMAN"; };
            class CommanderOptics2 : CommanderOptics2 { gunnerType = "OPF_GREN_CREWMAN"; };
            class GPMGTurretBMD2 : GPMGTurretBMD2 { gunnerType = "OPF_GREN_CREWMAN"; };
            class LeftBack2 : LeftBack2 { gunnerType = ""; };
            class RightBack2 : RightBack2 { gunnerType = ""; };
            class MainBack2 : MainBack2 { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmd_camo\data\sa_bmd2_01_rus3_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmd_camo\data\sa_bmd2_02_rus3_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmd_camo\data\sa_bmd2_03_rus3_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo3";

    };

    class OPF_GREN_BTR60 : rhs_btr60_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR 60";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_CREWMAN"; };
            class CommanderOptics : CommanderOptics { gunnerType = "OPF_GREN_CREWMAN"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\po_factions_fic\tka\Data\btr60_body_tka_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\rhs_a2port_armor\data\btr60_details_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "LOP_TKA";

    };

    class OPF_GREN_BRDM_ARMED : rhsgref_BRDM2_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BRDM (ARMED)";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_CREWMAN";

        class Turrets : Turrets {
            class CommanderOptics : CommanderOptics { gunnerType = "OPF_GREN_PILOT"; };
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_CREWMAN"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\BRDM2_3tone_01_co.paa'];_unit setObjectTextureGlobal [1,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\brdm2_3tone_02_co.paa'];_unit setObjectTextureGlobal [2,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\zbik_04_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "3tone";

    };

    class OPF_GREN_BRDM_AT : rhsgref_BRDM2_ATGM_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BRDM AT";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_CREWMAN"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\cdf_brdm2_atgm_01_co.paa'];_unit setObjectTextureGlobal [1,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\brdm2_02_camo_co.paa'];_unit setObjectTextureGlobal [2,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\zbik_04_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class OPF_GREN_ROVER_50 : LOP_IRA_Landrover_M2_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "ROVER .50";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_RIFLEMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_GUNNER"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'po_vehicles\lr\data\camo\lr_base_am_co.paa'];_unit setObjectTextureGlobal [1,'po_vehicles\lr\data\camo\lr_special_w_baf_co.paa'];_unit setObjectTextureGlobal [2,'po_vehicles\lr\data\camo\lr_mg-spg9_w_baf_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "LOP_AM";

    };

    class OPF_GREN_ROVER_AT : LOP_IRA_Landrover_SPG9_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "ROVER AT";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_RIFLEMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_GUNNER"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_TANK : rhs_sprut_vdv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "TANK";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_CREWMAN"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_WILDCAT : I_Heli_light_03_dynamicLoadout_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wildcat";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_PILOT";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_PILOT"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F_Enoch\Heli_Light_03\data\Heli_Light_03_base_EAF_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Supplies_F_Enoch\Ammoboxes\Data\AmmoBox_EAF_CO.paa'];_unit setObjectTextureGlobal [2,'\a3\Supplies_F_Enoch\Ammoboxes\Data\AmmoBox_signs_EAF_CA.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "EAF";

    };

    class OPF_GREN_WILDCAT_UNARMED : I_Heli_light_03_unarmed_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wildcata (Un-Armed)";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_PILOT";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_PILOT"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F_Enoch\Heli_Light_03\data\Heli_Light_03_base_EAF_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Supplies_F_Enoch\Ammoboxes\Data\AmmoBox_EAF_CO.paa'];_unit setObjectTextureGlobal [2,'\a3\Supplies_F_Enoch\Ammoboxes\Data\AmmoBox_signs_EAF_CA.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "EAF";

    };

    class OPF_GREN_AA_PLANE : I_Plane_Fighter_04_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA Plane";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_PILOT";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'a3\air_f_jets\plane_fighter_04\data\Fighter_04_fuselage_01_co.paa'];_unit setObjectTextureGlobal [1,'a3\air_f_jets\plane_fighter_04\data\Fighter_04_fuselage_02_co.paa'];_unit setObjectTextureGlobal [2,'a3\air_f_jets\plane_fighter_04\data\fighter_04_misc_01_co.paa'];_unit setObjectTextureGlobal [3,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_04_ca.paa'];_unit setObjectTextureGlobal [4,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_04_ca.paa'];_unit setObjectTextureGlobal [5,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_08_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "CamoGrey";

    };

    class OPF_GREN_CAS_PLANE : I_Plane_Fighter_03_dynamicLoadout_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "CAS PLANE";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_PILOT";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Air_F_Gamma\Plane_Fighter_03\Data\Plane_Fighter_03_body_1_greyhex_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Air_F_Gamma\Plane_Fighter_03\Data\Plane_Fighter_03_body_2_greyhex_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Grey";

    };

    class OPF_GREN_TRUCK_AMMO : rhs_gaz66_ammo_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Truck (AMMO)";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_RIFLEMAN";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsafrf\addons\rhs_gaz66\data\gaz66ru_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\rhs_gaz66\data\tentru_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "camo";

    };

    class OPF_GREN_TRUCK_FUEL : RHS_Ural_Fuel_MSV_01_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Truck (FUEL)";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_RIFLEMAN";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_kabina_camo_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_open_cdf_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [6,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [7,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [8,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [9,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [10,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_fuel_cdf_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class OPF_GREN_TRUCK_REPAIR : RHS_Ural_Repair_MSV_01_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Truck (REPAIR)";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_RIFLEMAN";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_kabina_rus_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_repair_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class OPF_GREN_ZSU : rhs_zsu234_aa_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "ZSU";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_CREWMAN"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\po_factions_me\IRAN\data\zsu_01_iran_co.paa'];_unit setObjectTextureGlobal [1,'\po_factions_me\IRAN\data\zsu_02_iran_co.paa'];_unit setObjectTextureGlobal [2,'\po_factions_me\IRAN\data\zsu_03_iran_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "LOP_IRAN";

    };

    class OPF_GREN_KAMAZ : rhs_kamaz5350_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "KAMAZ";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_RIFLEMAN";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "OPF_GREN_GUNNER"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "OPF_GREN_GUNNER"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "OPF_GREN_GUNNER"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_GREN_ARTILLERY : rhs_2s1_tv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Artillery";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "OPF_GREN_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_GREN_CREWMAN"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_hull_co.paa'];_unit setObjectTextureGlobal [1,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_turret_co.paa'];_unit setObjectTextureGlobal [2,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [3,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [4,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [5,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_red_co.paa'];_unit setObjectTextureGlobal [6,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [7,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_red_co.paa'];_unit setObjectTextureGlobal [8,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_red_co.paa'];_unit setObjectTextureGlobal [9,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [10,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_red_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "CDF";

    };

    class OPF_GREN_BOAT : O_T_Boat_Armed_01_hmg_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Boat Squad";
        side = 0;
        faction = "OPF_CAV_GREN_F";
        crew = "O_T_Soldier_F";

        class Turrets : Turrets {
            class FrontTurret : FrontTurret { gunnerType = ""; };
            class RearTurret : RearTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};