class CfgVehicles {

	class Cav_B_A_HelicopterAttackCoPilot_F;
	class Cav_B_A_HelicopterAttackPilot_F;
	class Cav_B_A_HelicopterCoPilot_F;
	class Cav_B_A_HelicopterCrew_F;
	class Cav_B_A_HelicopterPilot_F;
	class Cav_B_A_JTAC_F;
	class Cav_B_A_Pilot_F;
	class Cav_B_A_PlaneCoPilotLite_F;
	class Cav_B_A_PlanePilotLite_F;
	class Cav_B_A_TACP_F;
	class Cav_B_Armor_Commander_F;
	class Cav_B_Armor_Driver_F;
	class Cav_B_Armor_Gunner_F;
	class Cav_B_Armor_Loader_F;
	class Cav_B_B_AutomaticRifleman_F;
	class Cav_B_B_CombatLifeSaver_F;
	class Cav_B_B_Engineer_F;
	class Cav_B_B_EngineerTeamLeader_F;
	class Cav_B_B_FireTeamLeader_F;
	class Cav_B_B_Grenadier_F;
	class Cav_B_B_IFV_Commander_2_1_F;
	class Cav_B_B_IFV_Commander_2_2_F;
	class Cav_B_B_IFV_Commander_2_3_F;
	class Cav_B_B_IFV_Commander_2_4_F;
	class Cav_B_B_IFV_Driver_F;
	class Cav_B_B_IFV_Gunner_F;
	class Cav_B_B_MedicTeamLeader_F;
	class Cav_B_B_MedicTeamMember_F;
	class Cav_B_B_Officer_F;
	class Cav_B_B_PlatoonLeader_F;
	class Cav_B_B_PlatoonMedic_F;
	class Cav_B_B_Rifleman_F;
	class Cav_B_B_RiflemanAT_F;
	class Cav_B_B_RiflemanLAT_F;
	class Cav_B_B_SquadLeader_F;
	class Cav_B_C_AssistantMachineGunner_F;
	class Cav_B_C_AutomaticRifleman_F;
	class Cav_B_C_CombatLifeSaver_F;
	class Cav_B_C_FireTeamLeader_F;
	class Cav_B_C_Grenadier_F;
	class Cav_B_C_MachineGunner_F;
	class Cav_B_C_PlatoonLeader_F;
	class Cav_B_C_PlatoonMedic_F;
	class Cav_B_C_PlatoonSergeant_F;
	class Cav_B_C_Rifleman_F;
	class Cav_B_C_RiflemanAT_F;
	class Cav_B_C_RiflemanLAT_F;
	class Cav_B_C_SquadLeader_F;
	class Cav_B_Training_Drill_Instructor_F;

	// Alpha
	class Cav_B_A_AirController_F: Cav_B_A_TACP_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_AirController_Pegasus_1_F: Cav_B_A_TACP_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_AirController_Pegasus_2_F: Cav_B_A_TACP_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_coPilot_F: Cav_B_A_HelicopterAttackCoPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_Raider_1_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_Raider_2_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_Raider_3_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_Raider_4_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_Raven_1_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_Raven_2_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_Raven_3_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Att_Pilot_Raven_4_F: Cav_B_A_HelicopterAttackPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_coPilot_F: Cav_B_A_HelicopterCoPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_CrewChief_F: Cav_B_A_HelicopterCrew_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_DoorGunner_F: Cav_B_A_HelicopterCrew_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_Pilot_B1_F: Cav_B_A_HelicopterPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_Pilot_B2_F: Cav_B_A_HelicopterPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_Pilot_B3_F: Cav_B_A_HelicopterPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_Pilot_B4_F: Cav_B_A_HelicopterPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_Pilot_B5_F: Cav_B_A_HelicopterPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_Pilot_B6_F: Cav_B_A_HelicopterPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Helicopter_Tra_Pilot_F: Cav_B_A_HelicopterPilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_JFO_F: Cav_B_A_JTAC_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_JFO_Infidel_1_F: Cav_B_A_JTAC_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_JFO_Infidel_2_F: Cav_B_A_JTAC_F { scope = 1; scopeCurator = 0; };

	class Cav_B_A_Plane_Fighter_Pilot_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_1_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_2_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_3_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_4_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_5_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_6_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_7_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_8_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Fighter_Pilot_Hog_9_F: Cav_B_A_Pilot_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Transport_coPilot_F: Cav_B_A_PlaneCoPilotLite_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Transport_Pilot_F: Cav_B_A_PlanePilotLite_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Transport_Pilot_Titan_1_F: Cav_B_A_PlanePilotLite_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Transport_Pilot_Titan_2_F: Cav_B_A_PlanePilotLite_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Transport_Pilot_Titan_3_F: Cav_B_A_PlanePilotLite_F { scope = 1; scopeCurator = 0; };
	class Cav_B_A_Plane_Transport_Pilot_Titan_4_F: Cav_B_A_PlanePilotLite_F { scope = 1; scopeCurator = 0; };

	// Bravo

	class Cav_B_B_Atlas_Logistics_Officer_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Logistics_OpsNCO_3_5_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Logistics_OpsNCO_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Logistics_OpsOfficer_3_6_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Logistics_OpsOfficer_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Logistics_TeamLeader_3_3_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Logistics_TeamLeader_3_4_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Logistics_TeamLeader_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Logistics_TeamMember_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Medic_CombatMedic_F: Cav_B_B_MedicTeamMember_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Medic_TeamLeader_3_1_F: Cav_B_B_MedicTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Medic_TeamLeader_3_2_F: Cav_B_B_MedicTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Atlas_Medic_TeamLeader_F: Cav_B_B_MedicTeamLeader_F { scope = 1; scopeCurator = 0; };

	class Cav_B_B_Alpha_AutomaticRifleman_F: Cav_B_B_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Alpha_CombatLifeSaver_F: Cav_B_B_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Alpha_FireTeamLeader_F: Cav_B_B_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Alpha_Grenadier_F: Cav_B_B_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Alpha_Rifleman_F: Cav_B_B_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Alpha_RiflemanAT_F: Cav_B_B_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Alpha_RiflemanLAT_F: Cav_B_B_RiflemanLAT_F { scope = 1; scopeCurator = 0; };

	class Cav_B_B_Bravo_AutomaticRifleman_F: Cav_B_B_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Bravo_CombatLifeSaver_F: Cav_B_B_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Bravo_FireTeamLeader_F: Cav_B_B_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Bravo_Grenadier_F: Cav_B_B_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Bravo_Rifleman_F: Cav_B_B_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Bravo_RiflemanAT_F: Cav_B_B_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Bravo_RiflemanLAT_F: Cav_B_B_RiflemanLAT_F { scope = 1; scopeCurator = 0; };

	class Cav_B_B_Tank_Commander_F: Cav_B_Armor_Commander_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Tank_Commander_Saber_1_F: Cav_B_Armor_Commander_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Tank_Commander_Saber_2_F: Cav_B_Armor_Commander_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Tank_Commander_Saber_3_F: Cav_B_Armor_Commander_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Tank_Commander_Saber_4_F: Cav_B_Armor_Commander_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Tank_Driver_F: Cav_B_Armor_Driver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Tank_Gunner_F: Cav_B_Armor_Gunner_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Tank_Loader_F: Cav_B_Armor_Loader_F { scope = 1; scopeCurator = 0; };

	class Cav_B_B_Ifv_Commander_B_1_F: Cav_B_B_IFV_Commander_2_1_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Ifv_Commander_B_2_F: Cav_B_B_IFV_Commander_2_2_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Ifv_Commander_B_3_F: Cav_B_B_IFV_Commander_2_3_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Ifv_Commander_B_4_F: Cav_B_B_IFV_Commander_2_4_F { scope = 1; scopeCurator = 0; };

	class Cav_B_B_Mustang_CombatMedic_F: Cav_B_B_MedicTeamMember_F { scope = 1; scopeCurator = 0; };

	class Cav_B_B_LogisticsOpsNCO_Apollo_5_F: Cav_B_B_EngineerTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_LogisticsOpsNCO_F: Cav_B_B_EngineerTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_LogisticsOpsOfficer_Apollo_6_F: Cav_B_B_EngineerTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_LogisticsOpsOfficer_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_LogisticsTeamMember_F: Cav_B_B_Engineer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_LogisticTeamLeader_Apollo_1_F: Cav_B_B_EngineerTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_LogisticTeamLeader_Apollo_2_F: Cav_B_B_EngineerTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_LogisticTeamLeader_F: Cav_B_B_EngineerTeamLeader_F { scope = 1; scopeCurator = 0; };

	class Cav_B_B_Scout_Alpha_AutomaticRifleman_F: Cav_B_B_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Alpha_CombatLifeSaver_F: Cav_B_B_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Alpha_Grenadier_F: Cav_B_B_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Alpha_Rifleman_F: Cav_B_B_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Alpha_TeamLead_320_F: Cav_B_B_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Alpha_TeamLead_F: Cav_B_B_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_AutomaticRifleman_F: Cav_B_B_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Bravo_AutomaticRifleman_F: Cav_B_B_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Bravo_CombatLifeSaver_F: Cav_B_B_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Bravo_Grenadier_F: Cav_B_B_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Bravo_Rifleman_F: Cav_B_B_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Bravo_TeamLead_320_F: Cav_B_B_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Bravo_TeamLead_F: Cav_B_B_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_CombatLifeSaver_F: Cav_B_B_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Crew_F: Cav_B_B_IFV_Driver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Driver_F: Cav_B_B_IFV_Driver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Grenadier_F: Cav_B_B_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Gunner_F: Cav_B_B_IFV_Gunner_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Officer_F: Cav_B_B_Officer_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Platoon_Medic_2_7_F: Cav_B_B_PlatoonLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Platoon_Medic_F: Cav_B_B_PlatoonMedic_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_PlatoonLead_2_5_F: Cav_B_B_PlatoonLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_PlatoonLead_2_6_F: Cav_B_B_PlatoonLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_PlatoonLead_F: Cav_B_B_PlatoonLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_PlatoonMedic_2_7_F: Cav_B_B_PlatoonMedic_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_PlatoonMedic_F: Cav_B_B_PlatoonMedic_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Rifleman_F: Cav_B_B_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_SquadLeader_2_1_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_SquadLeader_2_2_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_SquadLeader_2_3_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_SquadLeader_2_4_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_SquadLeader_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Team_Leader_2_1_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Team_Leader_2_2_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Team_Leader_2_3_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Team_Leader_2_4_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Team_Leader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_TeamLead_320_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_TeamLead_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_Scout_Trooper_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };

	class Cav_B_B_SquadLeader_1_1_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_SquadLeader_1_2_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_SquadLeader_1_3_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_B_SquadLeader_1_4_F: Cav_B_B_SquadLeader_F { scope = 1; scopeCurator = 0; };


	// Charlie 
	class Cav_B_C_Alpha_AutomaticRifleman_F: Cav_B_C_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Alpha_CombatLifeSaver_F: Cav_B_C_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Alpha_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F  { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Alpha_Grenadier_F: Cav_B_C_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Alpha_Rifleman_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Alpha_RiflemanAT_F: Cav_B_C_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Alpha_RiflemanLAT_F: Cav_B_C_RiflemanLAT_F { scope = 1; scopeCurator = 0; };

	class Cav_B_C_Bravo_AutomaticRifleman_F: Cav_B_C_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Bravo_CombatLifeSaver_F: Cav_B_C_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Bravo_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Bravo_Grenadier_F: Cav_B_C_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Bravo_Rifleman_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Bravo_RiflemanAT_F: Cav_B_C_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Bravo_RiflemanLAT_F: Cav_B_C_RiflemanLAT_F { scope = 1; scopeCurator = 0; };

	class Cav_B_C_PlatoonLeader_Bandit_6_F: Cav_B_C_PlatoonLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_PlatoonLeader_Misfit_6_F: Cav_B_C_PlatoonLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_PlatoonMedic_Bandit_7_F: Cav_B_C_PlatoonMedic_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_PlatoonMedic_Misfit_7_F: Cav_B_C_PlatoonMedic_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_PlatoonSergeant_Bandit_5_F: Cav_B_C_PlatoonSergeant_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_PlatoonSergeant_Misfit_5_F: Cav_B_C_PlatoonSergeant_F { scope = 1; scopeCurator = 0; };

	class Cav_B_C_SquadLeader_Bandit_1_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_SquadLeader_Bandit_2_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_SquadLeader_Bandit_3_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_SquadLeader_Bandit_4_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };

	class Cav_B_C_SquadLeader_Misfit_1_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_SquadLeader_Misfit_2_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_SquadLeader_Misfit_3_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_SquadLeader_Misfit_4_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };

	class Cav_B_C_Weap_Alpha_AutomaticRifleman_F: Cav_B_C_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Alpha_CombatLifeSaver_F: Cav_B_C_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Alpha_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Alpha_Grenadier_F: Cav_B_C_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Alpha_Rifleman_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Alpha_RiflemanAT_F: Cav_B_C_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Alpha_RiflemanLAT_F: Cav_B_C_RiflemanLAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_AutomaticRifleman_F: Cav_B_C_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Bravo_AutomaticRifleman_F: Cav_B_C_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Bravo_CombatLifeSaver_F: Cav_B_C_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Bravo_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Bravo_Grenadier_F: Cav_B_C_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Bravo_Rifleman_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Bravo_RiflemanAT_F: Cav_B_C_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Bravo_RiflemanLAT_F: Cav_B_C_RiflemanLAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_CombatLifeSaver_F: Cav_B_C_CombatLifeSaver_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Grenadier_F: Cav_B_C_Grenadier_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_Rifleman_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_RiflemanAT_F: Cav_B_C_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_RiflemanLAT_F: Cav_B_C_RiflemanLAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_SquadLeader_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weap_SquadLeader_Havoc_1_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Alpha_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Alpha_Trooper_2_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Alpha_Trooper_3_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Alpha_Trooper_4_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Bravo_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Bravo_Trooper_2_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Bravo_Trooper_3_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Bravo_Trooper_4_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_M240B_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_M240B_Machinegunner_F: Cav_B_C_MachineGunner_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_M240B_MachinegunnerAmmoBearer_F: Cav_B_C_AssistantMachineGunner_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_MAAWS_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_MAAWS_MAAWSAssistant_F: Cav_B_C_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_MAAWS_MAAWSGunner_F: Cav_B_C_RiflemanAT_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Mortar_Assistant_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Mortar_AutomaticRifleman_F: Cav_B_C_AutomaticRifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Mortar_FireTeamLeader_F: Cav_B_C_FireTeamLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_Mortar_M224_F: Cav_B_C_Rifleman_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_SquadLeader_1_4_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_SquadLeader_2_4_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };
	class Cav_B_C_Weapons_SquadLeader_F: Cav_B_C_SquadLeader_F { scope = 1; scopeCurator = 0; };

	class Cav_B_Training_DrillInstructor_F: Cav_B_Training_Drill_Instructor_F { scope = 1; scopeCurator = 0; };

};