//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class OPF_CAV_AFRF_F {
        displayName = "Armed Forces of the Russian Federation";
        side = 0;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\Russia_CA.paa";
        priority = 0;
    };
};