//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class OPF_CAV_AFRF_F {
            name = "Armed Forces of the Russian Federation (AFRF)";

            class Infantry {
                name = "Infantry";

                class OPF_CAV_RIFLESQUAD {
                    name = "Rifle Squad";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_RAF_F";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SQDM";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAT";
                    };
                };

                class OPF_CAV_AT {
                    name = "Tank Hunter Section";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAT";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAT";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                };

                class OPF_CAV_AA {
                    name = "Aircraft Hunter Section";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAA";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAA";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                };

                class OPF_CAV_AIR_INF {
                    name = "Airborne Infantry";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_KA60";
                    };
                    class Unit1 {
                        position[] = {21,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_KAUNARMED";
                    };
                    class Unit2 {
                        position[] = {-21,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RAF_F";
                    };
                    class Unit3 {
                        position[] = {26,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit4 {
                        position[] = {-26,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit5 {
                        position[] = {31,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit6 {
                        position[] = {-31,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit7 {
                        position[] = {36,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-36,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SQDM";
                    };
                    class Unit9 {
                        position[] = {41,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAT";
                    };
                    class Unit10 {
                        position[] = {-41,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class OPF_CAV_SPECOP_SNIPER {
                    name = "Recon Sniper";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_R";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_SN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_G";
                    };
                };

                class OPF_CAV_SPECOP_INFIL {
                    name = "Infiltration Team";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_R";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_G";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_GU";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_Rifleman";
                    };
                };

                class OPF_CAV_SPECOP_TH {
                    name = "Tank Hunter Team";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_R";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_G";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_AT";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_Rifleman";
                    };
                };

                class OPF_CAV_SPEC_SQUAD {
                    name = "Specop Squad";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_R";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_G";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_G";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_GU";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_SN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPEC_AT";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SPECOP_Rifleman";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class OPF_CAV_UAZ_QRF {
                    name = "QRF Group (UAZ)";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_UAZ";
                    };
                    class Unit1 {
                        position[] = {5,-7,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_UAZ";
                    };
                };

                class OPF_CAV_TIGER_INF {
                    name = "Light Motorized Infantry (GAZ TIger)";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_TIGER";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GAZ_C";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RAF_F";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit4 {
                        position[] = {-10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit5 {
                        position[] = {15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SQDM";
                    };
                    class Unit6 {
                        position[] = {-15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                };

                class OPF_CAV_BTR_INF {
                    name = "Heavy Motorized Infantry (BTR)";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BTR80";
                    };
                    class Unit1 {
                        position[] = {6,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BTR80";
                    };
                    class Unit2 {
                        position[] = {-6,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RAF_F";
                    };
                    class Unit3 {
                        position[] = {11,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit4 {
                        position[] = {-11,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit5 {
                        position[] = {16,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit6 {
                        position[] = {-16,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit7 {
                        position[] = {21,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-21,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SQDM";
                    };
                    class Unit9 {
                        position[] = {26,-35,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAT";
                    };
                    class Unit10 {
                        position[] = {-26,-35,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class OPF_CAV_MECH_BMP {
                    name = "Mechanized Infantry (BMP)";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BMP2D";
                    };
                    class Unit1 {
                        position[] = {8,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BMP2D";
                    };
                    class Unit2 {
                        position[] = {-8,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RAF_F";
                    };
                    class Unit3 {
                        position[] = {13,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit4 {
                        position[] = {-13,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit5 {
                        position[] = {18,-23,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit6 {
                        position[] = {-18,-23,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit7 {
                        position[] = {23,-28,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-23,-28,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SQDM";
                    };
                    class Unit9 {
                        position[] = {28,-33,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAT";
                    };
                    class Unit10 {
                        position[] = {-28,-33,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                };

                class OPF_CAV_AIR_MECH {
                    name = "Airborne Mechanized Infantry (BMD)";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BMD";
                    };
                    class Unit1 {
                        position[] = {7,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_BMD";
                    };
                    class Unit2 {
                        position[] = {-7,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RAF_F";
                    };
                    class Unit3 {
                        position[] = {12,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit4 {
                        position[] = {-12,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit5 {
                        position[] = {17,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit6 {
                        position[] = {-17,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit7 {
                        position[] = {22,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit8 {
                        position[] = {-22,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_SQDM";
                    };
                    class Unit9 {
                        position[] = {27,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RIFLEAT";
                    };
                    class Unit10 {
                        position[] = {-27,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class OPF_CAV_ARMOR_GROUP {
                    name = "Armor Group";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_T80";
                    };
                    class Unit1 {
                        position[] = {7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T80";
                    };
                    class Unit2 {
                        position[] = {-7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T72";
                    };
                    class Unit3 {
                        position[] = {17,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T72";
                    };
                };

                class OPF_CAV_ARMOR_SECTION {
                    name = "Armor Section";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_T80";
                    };
                    class Unit1 {
                        position[] = {10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T72";
                    };
                };

                class OPF_CAV_ARMOR_MIX {
                    name = "Mixed Armor Group";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_T80";
                    };
                    class Unit1 {
                        position[] = {10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_T72";
                    };
                    class Unit2 {
                        position[] = {-10,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_ZSU";
                    };
                    class Unit3 {
                        position[] = {18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_ZSU";
                    };
                };

                class OPF_CAV_ZSU_SEC {
                    name = "ZSU Section";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_antiair.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_ZSU";
                    };
                    class Unit1 {
                        position[] = {8,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_ZSU";
                    };
                    class Unit2 {
                        position[] = {-8,-12,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BMP2D";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class OPF_CAV_HOW {
                    name = "Self Propelled Battery";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_2S1";
                    };
                    class Unit1 {
                        position[] = {10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_2S1";
                    };
                    class Unit2 {
                        position[] = {-10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_2S1";
                    };
                    class Unit3 {
                        position[] = {20,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_2S1";
                    };
                };

            };

            class Naval {
                name = "Naval";

                class OPF_CAV_BOAT_SEC {
                    name = "Boat Section";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_naval.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_BOAT";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_RAF_F";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_TEAMLEADER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GREN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_GUNNER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_MEDIC";
                    };
                };

            };

            class Air {
                name = "Air";

                class OPF_CAV_AA_WING {
                    name = "AA Wing";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_plane.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_AA";
                    };
                    class Unit1 {
                        position[] = {13,-26,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_AA";
                    };
                };

                class OPF_CAV_CAS_WING {
                    name = "CAS Wing";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_plane.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_CAS";
                    };
                    class Unit1 {
                        position[] = {15,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_CAS";
                    };
                };

                class OPF_CAV_KA_WING {
                    name = "KA-60 WING";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_CAV_KA60";
                    };
                    class Unit1 {
                        position[] = {21,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_CAV_KA60";
                    };
                };

            };


        };

    };
};