//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class OPF_CAV_AFRF_F {
            name = "Armed Forces of the Russian Federation";

            class Infantry {
                name = "Infantry";

                class OPF_AFRF_RIFLESQUAD {
                    name = "Rifle Squad";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class OPF_AFRF_SPECOP_SQUAD {
                    name = "Specop Squad";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_RIFLE";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_RIFLE";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_RIFLE";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_GREN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_GREN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_GUNNER";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_GUNNER";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_SNIPER";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_SNIPER";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_MARKSMAN";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SPECOP_MARKSMAN";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class OPF_AFRF_GAZ_SQUAD {
                    name = "GAZ Squad";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_GAZ_ARMED";
                    };
                    class Unit1 {
                        position[] = {6,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GAZ_ARMED";
                    };
                    class Unit2 {
                        position[] = {-6,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit3 {
                        position[] = {11,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit4 {
                        position[] = {-11,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit5 {
                        position[] = {16,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-16,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit7 {
                        position[] = {21,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit8 {
                        position[] = {-21,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit9 {
                        position[] = {26,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit10 {
                        position[] = {-26,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit11 {
                        position[] = {31,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit12 {
                        position[] = {-31,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                };

                class OPF_AFRF_KAMAZ_SQUAD {
                    name = "KAMAZ Squad";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit13 {
                        position[] = {36,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_KAMAZ";
                    };
                };

                class OPF_AFRF_BTR_SQUAD {
                    name = "BTR Squad";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_BTR80";
                    };
                    class Unit1 {
                        position[] = {6,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_BTR80A";
                    };
                    class Unit2 {
                        position[] = {-6,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit3 {
                        position[] = {11,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit4 {
                        position[] = {-11,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit5 {
                        position[] = {16,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit6 {
                        position[] = {-16,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit7 {
                        position[] = {21,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit8 {
                        position[] = {-21,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit9 {
                        position[] = {26,-35,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit10 {
                        position[] = {-26,-35,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit11 {
                        position[] = {31,-40,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit12 {
                        position[] = {-31,-40,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit13 {
                        position[] = {36,-45,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit14 {
                        position[] = {-36,-45,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class OPF_AFRF_A_MECH {
                    name = "Airborne Mechanized";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_BMD";
                    };
                    class Unit1 {
                        position[] = {7,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_BMD";
                    };
                    class Unit2 {
                        position[] = {-7,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit3 {
                        position[] = {12,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit4 {
                        position[] = {-12,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit5 {
                        position[] = {17,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit6 {
                        position[] = {-17,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit7 {
                        position[] = {22,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit8 {
                        position[] = {-22,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit9 {
                        position[] = {27,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit10 {
                        position[] = {-27,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit11 {
                        position[] = {32,-35,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit12 {
                        position[] = {-32,-35,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                };

                class OPF_AFRF_G_MECH {
                    name = "Mechanized Infantry";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_BMP";
                    };
                    class Unit1 {
                        position[] = {10,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_BMP";
                    };
                    class Unit2 {
                        position[] = {-10,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit3 {
                        position[] = {15,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit4 {
                        position[] = {-15,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit5 {
                        position[] = {20,-23,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit6 {
                        position[] = {-20,-23,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit7 {
                        position[] = {25,-28,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit8 {
                        position[] = {-25,-28,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit9 {
                        position[] = {30,-33,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit10 {
                        position[] = {-30,-33,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {35,-38,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit12 {
                        position[] = {-35,-38,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit13 {
                        position[] = {40,-43,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit14 {
                        position[] = {-40,-43,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class OPF_AFRF_T80_GROUP {
                    name = "T-80 Goup";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_T80";
                    };
                    class Unit1 {
                        position[] = {7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_T80";
                    };
                    class Unit2 {
                        position[] = {-7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_T80";
                    };
                    class Unit3 {
                        position[] = {14,-21,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_T80";
                    };
                };

                class OPF_AFRF_T80_MIXED {
                    name = "T-80 MIXED";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_T80";
                    };
                    class Unit1 {
                        position[] = {7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_T80";
                    };
                    class Unit2 {
                        position[] = {-7,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_ZSU";
                    };
                    class Unit3 {
                        position[] = {15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_ZSU";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class OPF_AFRF_Battery {
                    name = "Howitzer Battery";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_2S1";
                    };
                    class Unit1 {
                        position[] = {10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_2S1";
                    };
                    class Unit2 {
                        position[] = {-10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_2S1";
                    };
                    class Unit3 {
                        position[] = {20,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_2S1";
                    };
                };

            };

            class Naval {
                name = "Naval";

                class OPF_AFRF_BOATSQUAD {
                    name = "Boat Squad";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_naval.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_BOAT";
                    };
                    class Unit1 {
                        position[] = {9,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_BOAT";
                    };
                    class Unit2 {
                        position[] = {-9,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit3 {
                        position[] = {14,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit4 {
                        position[] = {-14,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit5 {
                        position[] = {19,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit6 {
                        position[] = {-19,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit7 {
                        position[] = {24,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit8 {
                        position[] = {-24,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit9 {
                        position[] = {29,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit10 {
                        position[] = {-29,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {34,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit12 {
                        position[] = {-34,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit13 {
                        position[] = {39,-49,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit14 {
                        position[] = {-39,-49,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                };

            };

            class Air {
                name = "Air";

                class OPF_AFRF_A_INF {
                    name = "Airborne Infantry";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_LEADER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GUNNER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_GREN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_SQDM";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_RIFLEMAN_AT";
                    };
                    class Unit13 {
                        position[] = {51,-54,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_KA60_UNARMED";
                    };
                    class Unit14 {
                        position[] = {-51,-54,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_KA60_UNARMED";
                    };
                };

                class OPF_AFRF_KA60_WING {
                    name = "KA-60 Wing";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_KA60";
                    };
                    class Unit1 {
                        position[] = {21,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_KA60";
                    };
                };

                class OPF_AFRF_AA_WING {
                    name = "AA WING";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_plane.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_AA_PLANE";
                    };
                    class Unit1 {
                        position[] = {13,-26,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_AA_PLANE";
                    };
                };

                class OPF_AFRF_CAS_WING {
                    name = "CAS WING";
                    side = 0;
                    faction = "OPF_CAV_AFRF_F";
                    icon = "\A3\ui_f\data\map\markers\nato\o_plane.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "OPF_AFRF_CASPLANE";
                    };
                    class Unit1 {
                        position[] = {15,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "OPF_AFRF_CASPLANE";
                    };
                };

            };


        };

    };
};