//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Heli_Light_02_dynamicLoadout_F;
    class O_Heli_Light_02_dynamicLoadout_F_OCimport_01 : O_Heli_Light_02_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class O_Heli_Light_02_dynamicLoadout_F_OCimport_02 : O_Heli_Light_02_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
        };
    };

    class O_Heli_Light_02_unarmed_F;
    class O_Heli_Light_02_unarmed_F_OCimport_01 : O_Heli_Light_02_unarmed_F { scope = 0; class EventHandlers; class Turrets; };
    class O_Heli_Light_02_unarmed_F_OCimport_02 : O_Heli_Light_02_unarmed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
        };
    };

    class O_Pilot_F;
    class O_Pilot_F_OCimport_01 : O_Pilot_F { scope = 0; class EventHandlers; };
    class O_Pilot_F_OCimport_02 : O_Pilot_F_OCimport_01 { class EventHandlers; };

    class rhs_t80ue1;
    class rhs_t80ue1_OCimport_01 : rhs_t80ue1 { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t80ue1_OCimport_02 : rhs_t80ue1_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_kamaz5350_msv;
    class rhs_kamaz5350_msv_OCimport_01 : rhs_kamaz5350_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_kamaz5350_msv_OCimport_02 : rhs_kamaz5350_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class RHS_Ural_Fuel_MSV_01;
    class RHS_Ural_Fuel_MSV_01_OCimport_01 : RHS_Ural_Fuel_MSV_01 { scope = 0; class EventHandlers; };
    class RHS_Ural_Fuel_MSV_01_OCimport_02 : RHS_Ural_Fuel_MSV_01_OCimport_01 { scope = 0; class EventHandlers; };

    class RHS_Ural_Repair_MSV_01;
    class RHS_Ural_Repair_MSV_01_OCimport_01 : RHS_Ural_Repair_MSV_01 { scope = 0; class EventHandlers; };
    class RHS_Ural_Repair_MSV_01_OCimport_02 : RHS_Ural_Repair_MSV_01_OCimport_01 { scope = 0; class EventHandlers; };

    class rhs_gaz66_ammo_msv;
    class rhs_gaz66_ammo_msv_OCimport_01 : rhs_gaz66_ammo_msv { scope = 0; class EventHandlers; };
    class rhs_gaz66_ammo_msv_OCimport_02 : rhs_gaz66_ammo_msv_OCimport_01 { scope = 0; class EventHandlers; };

    class rhs_tigr_m_3camo_msv;
    class rhs_tigr_m_3camo_msv_OCimport_01 : rhs_tigr_m_3camo_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_tigr_m_3camo_msv_OCimport_02 : rhs_tigr_m_3camo_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
        };
    };

    class rhs_tigr_sts_3camo_msv;
    class rhs_tigr_sts_3camo_msv_OCimport_01 : rhs_tigr_sts_3camo_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_tigr_sts_3camo_msv_OCimport_02 : rhs_tigr_sts_3camo_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class AGS_Turret;
        };
    };

    class rhs_btr80_msv;
    class rhs_btr80_msv_OCimport_01 : rhs_btr80_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_btr80_msv_OCimport_02 : rhs_btr80_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class Commander_Out;
        };
    };

    class rhs_btr80a_msv;
    class rhs_btr80a_msv_OCimport_01 : rhs_btr80a_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_btr80a_msv_OCimport_02 : rhs_btr80a_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class Commander_Out;
        };
    };

    class rhs_bmd2m;
    class rhs_bmd2m_OCimport_01 : rhs_bmd2m { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmd2m_OCimport_02 : rhs_bmd2m_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics2;
            class GPMGTurretBMD2;
            class LeftBack2;
            class RightBack2;
            class MainBack2;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class rhs_bmp3m_msv;
    class rhs_bmp3m_msv_OCimport_01 : rhs_bmp3m_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmp3m_msv_OCimport_02 : rhs_bmp3m_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class GPMGTurret1;
            class GPMGTurret2;
        };
    };

    class O_Boat_Armed_01_hmg_F;
    class O_Boat_Armed_01_hmg_F_OCimport_01 : O_Boat_Armed_01_hmg_F { scope = 0; class EventHandlers; class Turrets; };
    class O_Boat_Armed_01_hmg_F_OCimport_02 : O_Boat_Armed_01_hmg_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class FrontTurret;
            class RearTurret;
        };
    };

    class rhs_zsu234_aa;
    class rhs_zsu234_aa_OCimport_01 : rhs_zsu234_aa { scope = 0; class EventHandlers; class Turrets; };
    class rhs_zsu234_aa_OCimport_02 : rhs_zsu234_aa_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_Plane_Fighter_04_F;
    class I_Plane_Fighter_04_F_OCimport_01 : I_Plane_Fighter_04_F { scope = 0; class EventHandlers; };
    class I_Plane_Fighter_04_F_OCimport_02 : I_Plane_Fighter_04_F_OCimport_01 { scope = 0; class EventHandlers; };

    class I_Plane_Fighter_03_dynamicLoadout_F;
    class I_Plane_Fighter_03_dynamicLoadout_F_OCimport_01 : I_Plane_Fighter_03_dynamicLoadout_F { scope = 0; class EventHandlers; };
    class I_Plane_Fighter_03_dynamicLoadout_F_OCimport_02 : I_Plane_Fighter_03_dynamicLoadout_F_OCimport_01 { scope = 0; class EventHandlers; };

    class rhs_2s1_tv;
    class rhs_2s1_tv_OCimport_01 : rhs_2s1_tv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_2s1_tv_OCimport_02 : rhs_2s1_tv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class OPF_AFRF_KA60 : O_Heli_Light_02_dynamicLoadout_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "KA-60 ARMED";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_PILOT";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "OPF_AFRF_PILOT"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F_Heli\Heli_Light_02\Data\Heli_Light_02_ext_OPFOR_V2_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Blackcustom";

    };

    class OPF_AFRF_KA60_UNARMED : O_Heli_Light_02_unarmed_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "KA-60 UNARMED";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_PILOT";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "OPF_AFRF_PILOT"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F_Heli\Heli_Light_02\Data\Heli_Light_02_ext_OPFOR_V2_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Blackcustom";

    };

    class OPF_AFRF_PILOT : O_Pilot_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b43","rhs_zsh7a_mike_green_alt","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b43","rhs_zsh7a_mike_green_alt","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74un","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_aks74un","rhs_weap_pya"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9x19_17"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74un","rhs_acc_pgs64_74un","","rhs_acc_okp7_dovetail",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"FirstAidKit",4},{"rhs_mag_9x19_17",2,17}}},{"rhs_6b43",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1}}},{},"rhs_zsh7a_mike_green_alt","",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_T80 : rhs_t80ue1_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "T-80";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_AFRF_CREWMAN"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_t80u_camo\data\rhs_t80u_tricolor_01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_t80u_camo\data\rhs_t80u_tricolor_02b_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_t80u_camo\data\rhs_t80u_tricolor_03_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "tricolor";

    };

    class OPF_AFRF_CREWMAN : OPF_AFRF_PILOT {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6b23_digi_crew","rhs_tsh4","ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b23_digi_crew","rhs_tsh4","ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_pp2000","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_pp2000","rhs_weap_pya"};

        magazines[] = {"rhs_mag_9x19mm_7n21_20","rhs_mag_9x19_17","rhs_mag_9x19mm_7n21_20","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_mag_9x19mm_7n21_20","rhs_mag_9x19_17","rhs_mag_9x19mm_7n21_20","rhs_mag_9x19_17"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pp2000","","","rhs_acc_okp7_picatinny",{"rhs_mag_9x19mm_7n21_20",20},{},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"ACE_fieldDressing",4},{"ACE_packingBandage",4},{"ACE_morphine",4},{"ACE_tourniquet",4},{"rhs_mag_9x19_17",2,17},{"rhs_mag_9x19mm_7n21_20",1,20}}},{"rhs_6b23_digi_crew",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_mag_9x19mm_7n21_20",2,20}}},{},"rhs_tsh4","",{},{"ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_RIFLEMAN : OPF_AFRF_PILOT {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_ak74m_camo","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_ak74m_camo","rhs_weap_pya"};

        magazines[] = {"rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74m_camo","rhs_acc_dtk1983","rhs_acc_perst1ik","rhs_acc_okp7_dovetail",{"rhs_30Rnd_545x39_7N22_camo_AK",30},{},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"FirstAidKit",4},{"rhs_mag_9x19_17",2,17}}},{"rhs_6sh92_digi",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_30Rnd_545x39_7N22_camo_AK",6,30}}},{"rhs_assault_umbts",{}},"rhs_6b47","G_Balaclava_oli",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_KAMAZ : rhs_kamaz5350_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "KAMAZ";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_RIFLEMAN";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "OPF_AFRF_RIFLEMAN"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "OPF_AFRF_RIFLEMAN"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "OPF_AFRF_RIFLEMAN"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsafrf\addons\rhs_kamaz\data\Kamaz5350_cabin_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\rhs_kamaz\data\Kamaz5350_cargo_co.paa'];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\rhs_kamaz\data\kamaz5350_base_co.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\rhs_kamaz\data\bed\rhs_kamaz_bed_co.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\rhs_kamaz\data\bed\rhs_kamaz_cover_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class OPF_AFRF_URAL_FUEL : RHS_Ural_Fuel_MSV_01_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "URAL (FUEL)";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "rhs_msv_driver";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car_camo\data\ural_kabina_sand_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car_camo\data\ural_open_sand_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [4,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [5,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [6,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [7,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [8,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [9,'rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [10,'rhsafrf\addons\rhs_a2port_car_camo\data\ural_fuel_sand_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "rhs_sand";

    };

    class OPF_AFRF_URAL_REPAIR : RHS_Ural_Repair_MSV_01_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "URAL (REPAIR)";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "rhs_msv_driver";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_kabina_rus_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_repair_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class OPF_AFRF_GAZ_AMMO : rhs_gaz66_ammo_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ (AMMO)";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "rhs_msv_driver";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsafrf\addons\rhs_gaz66\data\gaz66ru_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\rhs_gaz66\data\tentru_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "camo";

    };

    class OPF_AFRF_GREN : OPF_AFRF_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadeir";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6sh92_digi_vog","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6sh92_digi_vog","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_ak74m_gp25","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_ak74m_gp25","rhs_weap_pya"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N10_AK","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74m_gp25","rhs_acc_dtk1983","","rhs_acc_okp7_dovetail",{"rhs_30Rnd_545x39_7N10_AK",30},{},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"FirstAidKit",4},{"rhs_mag_9x19_17",2,17},{"rhs_VOG25",2,1}}},{"rhs_6sh92_digi_vog",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_30Rnd_545x39_7N10_AK",6,30},{"rhs_VOG25",1,1}}},{"rhs_assault_umbts",{{"rhs_VOG25P",10,1},{"rhs_VOG25",8,1}}},"rhs_6b47","G_Balaclava_oli",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_GUNNER : OPF_AFRF_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Gunner";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_pkp","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_pkp","rhs_weap_pya"};

        magazines[] = {"rhs_100Rnd_762x54mmR","rhs_mag_9x19_17","rhs_100Rnd_762x54mmR","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_100Rnd_762x54mmR","rhs_mag_9x19_17","rhs_100Rnd_762x54mmR","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pkp","","","rhs_acc_okp7_dovetail",{"rhs_100Rnd_762x54mmR",100},{},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"FirstAidKit",4},{"rhs_mag_9x19_17",2,17}}},{"rhs_6sh92_digi",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_100Rnd_762x54mmR",1,100}}},{"rhs_assault_umbts",{{"rhs_100Rnd_762x54mmR",2,100}}},"rhs_6b47","G_Balaclava_oli",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_LEADER : OPF_AFRF_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Leader";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_ak74m_camo","rhs_weap_rshg2","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_ak74m_camo","rhs_weap_rshg2","rhs_weap_pya"};

        magazines[] = {"rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74m_camo","rhs_acc_dtk1983","rhs_acc_perst1ik","rhs_acc_okp7_dovetail",{"rhs_30Rnd_545x39_7N22_camo_AK",30},{},""},{"rhs_weap_rshg2","","","",{},{},""},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"ACE_fieldDressing",4},{"ACE_packingBandage",4},{"ACE_morphine",4},{"ACE_tourniquet",4},{"rhs_mag_9x19_17",2,17}}},{"rhs_6sh92_digi",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_30Rnd_545x39_7N22_camo_AK",6,30}}},{"rhs_assault_umbts",{}},"rhs_6b47","G_Balaclava_oli",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_SPECOP_RIFLE : OPF_AFRF_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Rifleman";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_gorka_r_y";

        linkedItems[] = {"rhs_6sh92_digi_radio","rhs_Booniehat_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6sh92_digi_radio","rhs_Booniehat_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74m_zenitco01","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_ak74m_zenitco01","rhs_weap_pya"};

        magazines[] = {"rhs_30Rnd_545x39_7N22_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_AK","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N22_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_AK","rhs_mag_9x19_17"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74m_zenitco01","rhs_acc_tgpa","rhs_acc_perst3","rhs_acc_okp7_dovetail",{"rhs_30Rnd_545x39_7N22_AK",30},{},"rhs_acc_grip_rk2"},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_gorka_r_y",{{"ACE_fieldDressing",4},{"ACE_packingBandage",4},{"ACE_morphine",4},{"ACE_tourniquet",4},{"rhs_mag_9x19_17",2,17}}},{"rhs_6sh92_digi_radio",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1}}},{},"rhs_Booniehat_digi","",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_SPECOP_GREN : OPF_AFRF_SPECOP_RIFLE {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Grenadier";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6sh92_digi_vog","rhs_Booniehat_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6sh92_digi_vog","rhs_Booniehat_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74mr_gp25","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_ak74mr_gp25","rhs_weap_pya"};

        magazines[] = {"rhs_VOG25","rhs_mag_9x19_17","rhs_VOG25","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_VOG25","rhs_mag_9x19_17","rhs_VOG25","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74mr_gp25","rhs_acc_tgpa","rhs_acc_perst3_top","rhs_acc_1p87",{},{"rhs_VOG25",1},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"FirstAidKit",4},{"rhs_mag_9x19_17",2,17},{"rhs_VOG25",2,1}}},{"rhs_6sh92_digi_vog",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_30Rnd_545x39_7N10_AK",5,30},{"rhs_VOG25",5,1},{"rhs_VOG25P",7,1}}},{"rhs_assault_umbts",{{"rhs_VOG25P",7,1}}},"rhs_Booniehat_digi","G_Balaclava_oli",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_SPECOP_GUNNER : OPF_AFRF_SPECOP_RIFLE {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Gunner";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_gorka_r_y";

        linkedItems[] = {"rhs_6sh92_digi_radio","rhs_Booniehat_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6sh92_digi_radio","rhs_Booniehat_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_pkp","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_pkp","rhs_weap_pya"};

        magazines[] = {"rhs_100Rnd_762x54mmR","rhs_mag_9x19_17","rhs_100Rnd_762x54mmR","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_100Rnd_762x54mmR","rhs_mag_9x19_17","rhs_100Rnd_762x54mmR","rhs_mag_9x19_17"};

        backpack = "rhs_sidor";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pkp","","","rhs_acc_okp7_dovetail",{"rhs_100Rnd_762x54mmR",100},{},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_gorka_r_y",{{"ACE_fieldDressing",4},{"ACE_packingBandage",4},{"ACE_morphine",4},{"ACE_tourniquet",4},{"rhs_mag_9x19_17",2,17}}},{"rhs_6sh92_digi_radio",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_100Rnd_762x54mmR",1,100}}},{"rhs_sidor",{{"rhs_100Rnd_762x54mmR",2,100}}},"rhs_Booniehat_digi","",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_SPECOP_SNIPER : OPF_AFRF_SPECOP_RIFLE {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Sniper";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_gorka_r_y";

        linkedItems[] = {"rhs_6sh92_digi","rhs_fieldcap_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6sh92_digi","rhs_fieldcap_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_t5000","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_t5000","rhs_weap_pya"};

        magazines[] = {"rhs_5Rnd_338lapua_t5000","rhs_mag_9x19_17","rhs_5Rnd_338lapua_t5000","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_5Rnd_338lapua_t5000","rhs_mag_9x19_17","rhs_5Rnd_338lapua_t5000","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_t5000","","","rhs_acc_dh520x56",{"rhs_5Rnd_338lapua_t5000",5},{},"rhs_acc_harris_swivel"},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_gorka_r_y",{{"ACE_fieldDressing",4},{"ACE_packingBandage",4},{"ACE_morphine",4},{"ACE_tourniquet",4},{"rhs_mag_9x19_17",2,17},{"rhs_5Rnd_338lapua_t5000",3,5}}},{"rhs_6sh92_digi",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_5Rnd_338lapua_t5000",12,5},{"rhs_mag_9x19_17",4,17}}},{"rhs_assault_umbts",{}},"rhs_fieldcap_digi","",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_SPECOP_MARKSMAN : OPF_AFRF_SPECOP_SNIPER {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specop Marksman";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_gorka_r_y";

        linkedItems[] = {"rhs_6sh92_digi","rhs_fieldcap_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6sh92_digi","rhs_fieldcap_digi","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_svds","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_svds","rhs_weap_pya"};

        magazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_mag_9x19_17","rhs_10Rnd_762x54mmR_7N1","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_mag_9x19_17","rhs_10Rnd_762x54mmR_7N1","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_svds","rhs_acc_tgpv2","","rhs_acc_pso1m21",{"rhs_10Rnd_762x54mmR_7N1",10},{},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_gorka_r_y",{{"ACE_fieldDressing",4},{"ACE_packingBandage",4},{"ACE_morphine",4},{"ACE_tourniquet",4},{"rhs_mag_9x19_17",2,17},{"rhs_10Rnd_762x54mmR_7N1",1,10}}},{"rhs_6sh92_digi",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_10Rnd_762x54mmR_7N1",6,10}}},{"rhs_assault_umbts",{}},"rhs_fieldcap_digi","",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_SQDM : OPF_AFRF_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_ak74m_camo","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_ak74m_camo","rhs_weap_pya"};

        magazines[] = {"rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74m_camo","rhs_acc_dtk1983","rhs_acc_perst1ik","rhs_acc_nita",{"rhs_30Rnd_545x39_7N22_camo_AK",30},{},""},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"FirstAidKit",4},{"rhs_mag_9x19_17",2,17}}},{"rhs_6sh92_digi",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_30Rnd_545x39_7N22_camo_AK",6,30}}},{"rhs_assault_umbts",{}},"rhs_6b47","G_Balaclava_oli",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_RIFLEMAN_AT : OPF_AFRF_RIFLEMAN {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 0;
        faction = "OPF_CAV_AFRF_F";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_emr_patchless";

        linkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6sh92_digi","rhs_6b47","ItemMap","ItemGPS","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_ak74m_camo","rhs_weap_rpg75","rhs_weap_pya"};
        respawnWeapons[] = {"rhs_weap_ak74m_camo","rhs_weap_rpg75","rhs_weap_pya"};

        magazines[] = {"rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17","rhs_30Rnd_545x39_7N22_camo_AK","rhs_mag_9x19_17"};

        backpack = "rhs_assault_umbts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74m_camo","rhs_acc_dtk1983","rhs_acc_perst1ik","rhs_acc_okp7_dovetail",{"rhs_30Rnd_545x39_7N22_camo_AK",30},{},""},{"rhs_weap_rpg75","","","",{},{},""},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"rhs_uniform_emr_patchless",{{"FirstAidKit",4},{"rhs_mag_9x19_17",2,17}}},{"rhs_6sh92_digi",{{"SmokeShell",4,1},{"SmokeShellBlue",1,1},{"rhs_30Rnd_545x39_7N22_camo_AK",6,30}}},{"rhs_assault_umbts",{}},"rhs_6b47","",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_GAZ_UNARMED : rhs_tigr_m_3camo_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ (UN-ARMED)";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_GREN";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "OPF_AFRF_GUNNER"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_GAZ_ARMED : rhs_tigr_sts_3camo_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ (ARMED)";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_GREN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_AFRF_GUNNER"; };
            class AGS_Turret : AGS_Turret { gunnerType = "rhs_msv_grenadier"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class OPF_AFRF_BTR80 : rhs_btr80_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR 80";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_AFRF_CREWMAN"; };
            class CommanderOptics : CommanderOptics { gunnerType = "OPF_AFRF_CREWMAN"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80_01_tri01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80_02_tri01_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80_03_tri01_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "tricolourhard";

    };

    class OPF_AFRF_BTR80A : rhs_btr80a_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR 80 A";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_AFRF_CREWMAN"; };
            class CommanderOptics : CommanderOptics { gunnerType = "OPF_AFRF_CREWMAN"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80a_01_tri01_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80a_02_tri01_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_btr80_camo\data\rhs_btr80a_03_tri01_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "tricolourhard";

    };

    class OPF_AFRF_BMD : rhs_bmd2m_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BMD";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_AFRF_CREWMAN"; };
            class CommanderOptics2 : CommanderOptics2 { gunnerType = "OPF_AFRF_CREWMAN"; };
            class GPMGTurretBMD2 : GPMGTurretBMD2 { gunnerType = "OPF_AFRF_CREWMAN"; };
            class LeftBack2 : LeftBack2 { gunnerType = ""; };
            class RightBack2 : RightBack2 { gunnerType = ""; };
            class MainBack2 : MainBack2 { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmd_camo\data\sa_bmd2_01_rus4_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmd_camo\data\sa_bmd2_02_rus4_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmd_camo\data\sa_bmd2_03_rus4_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo4";

    };

    class OPF_AFRF_BMP : rhs_bmp3m_msv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BMP";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_AFRF_CREWMAN"; };
            class GPMGTurret1 : GPMGTurret1 { gunnerType = "rhs_msv_rifleman"; };
            class GPMGTurret2 : GPMGTurret2 { gunnerType = "rhs_msv_rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_01_3m_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_02_co.paa'];_unit setObjectTextureGlobal [2,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_03_3m_co.paa'];_unit setObjectTextureGlobal [3,'rhsafrf\addons\rhs_bmp3\data\rhs_bmp3_04_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class OPF_AFRF_BOAT : O_Boat_Armed_01_hmg_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "BOAT";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_GREN";

        class Turrets : Turrets {
            class FrontTurret : FrontTurret { gunnerType = "OPF_AFRF_GUNNER"; };
            class RearTurret : RearTurret { gunnerType = "OPF_AFRF_GUNNER"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Boat_F\Boat_Armed_01\Data\Boat_Armed_01_ext_opfor_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\boat_f\Boat_Armed_01\data\Boat_Armed_01_int_opfor_co.paa'];_unit setObjectTextureGlobal [2,'\A3\boat_f\Boat_Armed_01\data\Boat_Armed_01_crows_OPFOR_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Opfor";

    };

    class OPF_AFRF_ZSU : rhs_zsu234_aa_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "ZSU";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_CREWMAN";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "OPF_AFRF_CREWMAN"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\po_factions_me\IRAN\data\zsu_01_iran_co.paa'];_unit setObjectTextureGlobal [1,'\po_factions_me\IRAN\data\zsu_02_iran_co.paa'];_unit setObjectTextureGlobal [2,'\po_factions_me\IRAN\data\zsu_03_iran_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "LOP_IRAN";

    };

    class OPF_AFRF_AA_PLANE : I_Plane_Fighter_04_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA PLANE";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_PILOT";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'a3\air_f_jets\plane_fighter_04\data\Fighter_04_fuselage_01_co.paa'];_unit setObjectTextureGlobal [1,'a3\air_f_jets\plane_fighter_04\data\Fighter_04_fuselage_02_co.paa'];_unit setObjectTextureGlobal [2,'a3\air_f_jets\plane_fighter_04\data\fighter_04_misc_01_co.paa'];_unit setObjectTextureGlobal [3,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_04_ca.paa'];_unit setObjectTextureGlobal [4,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_04_ca.paa'];_unit setObjectTextureGlobal [5,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_08_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "CamoGrey";

    };

    class OPF_AFRF_CASPLANE : I_Plane_Fighter_03_dynamicLoadout_F_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "CAS PLANE";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "OPF_AFRF_PILOT";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Air_F_Gamma\Plane_Fighter_03\Data\Plane_Fighter_03_body_1_greyhex_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Air_F_Gamma\Plane_Fighter_03\Data\Plane_Fighter_03_body_2_greyhex_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Grey";

    };

    class OPF_AFRF_2S1 : rhs_2s1_tv_OCimport_02 {
        author = "CPL.Citarelli.D";
        scope = 2;
        scopeCurator = 2;
        displayName = "2S1";
        side = 0;
        faction = "OPF_CAV_AFRF_F";
        crew = "rhs_msv_crew";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_hull_co.paa'];_unit setObjectTextureGlobal [1,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_turret_co.paa'];_unit setObjectTextureGlobal [2,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [3,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [4,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [5,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_red_co.paa'];_unit setObjectTextureGlobal [6,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [7,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_red_co.paa'];_unit setObjectTextureGlobal [8,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_red_co.paa'];_unit setObjectTextureGlobal [9,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_green_co.paa'];_unit setObjectTextureGlobal [10,'rhsgref\addons\rhsgref_vehicles_ret\data\cdf\rhs_2s1_cdf_suspension_red_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "CDF";

    };

};