name: Testing
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  push:
    branches: main

jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      if: always()
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      if: always()
      run: python3 tools/config_style_checker.py
    - name: Validate Stringtables
      if: always()
      run: python3 tools/stringtable_validator.py
      continue-on-error: true
    - name: Check Strings
      if: always()
      run: python3 tools/check_strings.py
    # - name: Check for BOM
    #   uses: arma-actions/bom-check@master

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives

  hemtt:
    name: HEMTT Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: HEMTT check
        run: hemtt check
