name: Build
on:
  release:
      types: [ published, prereleased ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1
            - name: Run HEMTT build
              run: ./tools/deploy.sh
            - name: Upload Release
              uses: actions/upload-artifact@v2
              with:
                  path: release/*.zip