name: Build
on:
  release:
      types: [ published, prereleased ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: acemod/armake:master
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Build using HEMTT
      uses: arma-actions/hemtt@master
      with:
        command: build --ci --release
    - name: Upload Release
      uses: JasonEtco/upload-to-release@master
      with:
        args: release/Compositions-${{ steps.get_version.outputs.VERSION }}.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}