name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selected deploy enviroment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - live
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Checkout pull request
      uses: actions/checkout@v4
    - name: Run HEMTT release
      run: hemtt release
    - name: DEBUG ending...
      run: |
        Write-Host "Environment: $ENVIRONMENT"
        Get-Content -Path .hemttout\
      env:
        ENVIRONMENT: ${{ inputs.environment }}