name: Publish
run-name: Publishing ${{github.ref_name}} to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Selected deploy environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - live
jobs:
  publish:
    name: Publish to steam workshop
    runs-on: windows-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Obtaining release
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        if: ${{ inputs.environment == 'live' }}
        run: |
          .\tools\deploy-getRelease.ps1 ${{github.ref_name}}
          Get-ChildItem -Path . -ErrorAction SilentlyContinue
      - name: Deploy release build to workshop
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        if: ${{ inputs.environment == 'live' }}
        run: |
          Copy-Item "resources\payload_dev.vdf" payload.vdf
          steamcmd.exe +login "$env:STEAM_USERNAME" "$env:STEAM_PASSWORD" +workshop_build_item D:\a\7CavAddon\7CavAddon\payload.vdf +quit
    

      - name: Run HEMTT build
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        if: ${{ inputs.environment == 'dev' }}
        run: |
          hemtt build

      - name: Deploy dev build to workshop
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        if: ${{ inputs.environment == 'dev' }}
        run: |
          Copy-Item "resources\payload_dev.vdf" payload.vdf
          steamcmd.exe +login "$env:STEAM_USERNAME" "$env:STEAM_PASSWORD" +workshop_build_item D:\a\7CavAddon\7CavAddon\payload.vdf +quit